### ISSUE TITLE
Add other Github flavored markdown...

### ISSUE THREAD

**Issue by thakyZ** [ArmandGrillet/Mado#116]
There seems to be some markdown (I don't know what the "code" is called) "code". Such as the checkmark boxes which are written as `- [x]` and `- [ ]`. Images seem to not work in either regular style and reference style (`![alt text](image)` or `![alt text][ref] [ref]: link`). I couldn't test YouTube videos but I don't believing they work either since images don't work but you may have made it work, I just don't know.
Now I have tested all of the ones that I could find, and all of them seem to work except the ones that are listed above. There is still emojis, but I don't know if you want to add those.

**Comment by ArmandGrillet** [comment]
In the same order as your questions:
- You cannot add checkmark boxes, I'm not sure how to implement them.
- You cannot add embedded YouTube videos because it violates this Chrome Content Security Policy directive: "frame-src 'self' blob: filesystem: data: chrome-extension-resource:"
- You can add online images:
![capture d ecran 2015-10-10 a 22 52 37](https://cloud.githubusercontent.com/assets/2117580/10413242/0281a826-6fa2-11e5-8808-afcb8eed2d4b.png)
- You can add local images, make sure you've added the image's directory to your galleries using the "Offline Image" button in Mado.
![capture d ecran 2015-10-10 a 23 00 22](https://cloud.githubusercontent.com/assets/2117580/10413269/37ee0be8-6fa3-11e5-8530-764c928880fc.png)
- You can add some emojis.
![capture d ecran 2015-10-10 a 23 05 06](https://cloud.githubusercontent.com/assets/2117580/10413285/9a74277a-6fa3-11e5-8255-d84f3908aa95.png)
